import Head from 'next/head';
import Image from 'next/image';
import { Inter } from 'next/font/google';
import styles from '@/styles/Home.module.css';
import Header from '@/components/Header';
import Banner from '@/components/Banner';
import SmallCard from '@/components/SmallCard';
import MediumCard from '@/components/MediumCard';
import LargeCard from '@/components/LargeCard';
import Footer from '@/components/Footer';

type Data = {
  data: Item[];
  cardData: CardItem[];
};

type Item = {
  img: string;
  location: string;
  distance: string;
};
type CardItem = {
  img: string;
  title: string;
};

export default function Home({ data, cardData }: Data) {
  return (
    <>
      <Head>
        <title>Next Booking</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <Banner />
      <main className="max-w-7xl mx-auto px-8 sm:px-16">
        <section className="pt-6">
          <h2 className="text-4xl font-semibold pb-5">Explore Nearby</h2>
          <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 xl:grid-cols-4">
            {data.map((item: Item, i: number) => (
              <>
                <SmallCard
                  img={item.img}
                  distance={item.distance}
                  location={item.location}
                  key={i}
                />
              </>
            ))}
          </div>
        </section>
        <section>
          <h2 className="text-4xl font-semibold py-8">Live Anywhere</h2>
          <div className="flex space-x-3 overflow-scroll scrollbar-hide p-3 -ml-3">
            {cardData.map((item: CardItem, i: number) => (
              <>
                <MediumCard key={i} img={item.img} title={item.title} />
              </>
            ))}
          </div>
        </section>
        <LargeCard
          img="https://res.cloudinary.com/dbejjbpof/video/upload/v1679377914/45326-travel_fdixxn.mp4"
          title="Find Your Next Trip"
          description="NextBooking Recommendations"
          buttonText="Get Inspired"
        />
      </main>
      <Footer />
    </>
  );
}

export async function getStaticProps() {
  const exploreResponse = await fetch('http://localhost:3000/api/hello');
  const data = await exploreResponse.json();

  const cardData = await fetch('http://localhost:3000/api/cards').then((res) =>
    res.json()
  );

  return {
    props: {
      data,
      cardData,
    },
  };
}
