import Head from 'next/head';
import Image from 'next/image';
import { Inter } from 'next/font/google';
import styles from '@/styles/Home.module.css';

import Banner from '@/components/Banner';
import SmallCard from '@/components/SmallCard';
import MediumCard from '@/components/MediumCard';
import LargeCard from '@/components/LargeCard';
import Footer from '@/components/Footer';
import Header from '@/components/Header';
import Posts from '@/components/Posts';

type Data = {
  data: Item[];
  cardData: CardItem[];
  PostData: Posts[];
  Iplocation: {
    city: string;
  };
};

type Posts = {
  image: string;
  title: string;
};

type Item = {
  img: string;
  location: string;
  distance: string;
};
type CardItem = {
  img: string;
  title: string;
};

export default function Home({ data, cardData, Iplocation, PostData }: Data) {
  return (
    <>
      <Head>
        <title>Next Booking</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <Banner />
      <main className="max-w-7xl mx-auto px-8 sm:px-16">
        <section className="pt-4">
          <h2 className="text-4xl font-semibold pb-1 text-neutral-800">
            Popular Destinations
          </h2>
          <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 xl:grid-cols-4">
            {data.map((item: Item, i: number) => (
              <>
                <SmallCard
                  img={item.img}
                  distance={item.distance}
                  location={item.location}
                  key={i}
                />
              </>
            ))}
          </div>
        </section>
        <section className="mt-12">
          <h2 className="text-4xl font-semibold pb-1 text-neutral-800">
            Get Inspired
          </h2>
          <p className="text-neutral-600">With Our Creators recent Posts</p>
          <Posts PostData={PostData} />
        </section>

        {/* <section>
          <h2 className="text-4xl font-semibold py-8">Live Anywhere</h2>
          <div className="flex space-x-3 overflow-scroll scrollbar-hide p-3 -ml-3">
            {cardData.map((item: CardItem, i: number) => (
              <>
                <MediumCard key={i} img={item.img} title={item.title} />
              </>
            ))}
          </div>
        </section> */}
        <LargeCard
          img="https://res.cloudinary.com/dbejjbpof/video/upload/v1679377914/45326-travel_fdixxn.mp4"
          title="Find Your Next Trip"
          description="NextBooking Recommendations"
          buttonText="Get Inspired"
        />
      </main>
      <Footer />
    </>
  );
}

export async function getStaticProps() {
  const exploreResponse = await fetch('http://localhost:3000/api/hello');
  const data = await exploreResponse.json();

  const cardData = await fetch('http://localhost:3000/api/cards').then((res) =>
    res.json()
  );
  const PostData = await fetch('http://localhost:3000/api/posts').then((res) =>
    res.json()
  );

  // const Iplocation = await fetch(
  //   'https://ipinfo.io/json?token=4cf5770462499b'
  // ).then((res) => res.json());

  return {
    props: {
      data,
      cardData,
      PostData,
      // Iplocation,
    },
  };
}
